### ISSUE TITLE
Remapping of concepts to another domain

### ISSUE THREAD

**Issue by Anne0507** [thehyve/ohdsi-omop-pioneer#10]
For the current condition domain: 

- 441413 - Death of unknown cause (mapping to Death or Observation domain?)
- 4297089 - Natural death (mapping to Death or Observation domain?)
- Definitely prostate cancer, not mapped now, but important to do.

For the current Observation domain:

The following concepts contains condition concepts, mapping to condition occurrence?
- 4127611 - Tumour stage T2b 
- 4266674 – N0 category 
- 4149726 – M0 category 
- 4041008 – G2 grade 
- 4211973 - Gleason grade score 7 out of 10
- 4129916 - Tumor stage T1c 
- 4204361 - G1 grade 
- 4250166 - Gleason grade score 5 out of 10 
- 4129917 - Tumor stage T2a 
- 4224785 -  Gleason grade score 6 out of 10
- 4129918 - Tumor stage T3a 
- 4203608 - N1 category 
- 4264742 - G3 grade 
- 4074238 - Gleason grade score 10 out of 10
- 4129127 - Tumor stage T2c 
- 4195718 - NX category 
- 4098852 – MX category 
- 4140825 - Gleason grade score 8 out of 10 
- 4130416 – Tumor stage T3b 
- 4205430 - M1 category
- 4129126 – Tumor stage T1b 
- 4240465 – Gleason grade score 9 out of 10 
- 4127612 – Tumor stage T4a
- 4282467 - TX category 
 - 4130414 – Tumor stage T1a
- 4086970 – Gleason grade score 4 out of 10 
- 4129920 – Tumor stage T4b 
- 4129919 – Tumor stage T3c 
- 4300243 – postoperative complication 
- 4263599 – N2 category
- 4263220 – Gleason grade 3 out of 10
- 4172456 – Gleason grade score 2 out of 10
- 4120176 – G4 grade 
- 4239307 – N3 category 

At the moment there are no concepts for routine recall, Y3b, NA, T2. Can't we make a custom concept for "routine recall"? Is Y3b a typo? Do we need a custom concept for T2?

For the Procedure domain, the following concept has an observation concept, do we want to map it to Observation?
 – 4190466 - No anti-cancer treatment – watchful waiting

For the Measurement domain:
- 2617205 – Prostate cancer screening; digital rectal examination (procedure concept)
- 4268703 – Biopsy finding (condition concept)

**Comment by MaximMoinat** [comment]
This is erpsc specific right? Could you add it to the ohdsi-etl-erspc repo?
https://github.com/thehyve/ohdsi-etl-erspc
