### ISSUE TITLE
Add source concepts - MK

### ISSUE THREAD

**Issue by RomainTching** [thehyve/ohdsi-omop-pioneer#33]
As described in reports for mapping the Martini Klinik dataset, we would like to suggest the addition of 6 custom concepts to the PIONEER vocabulary:
•	2000000198 “Volume of the Gleason Primary part of the tumour”
•	2000000199 “Percentage of the total volume of the tumour occupied by the Gleason Primary part of the tumour”
•	2000000200 “Volume of the Gleason Secondary part of the tumour”
•	2000000201 “Percentage of the total volume of the tumour occupied by the Gleason Secondary part of the tumour”
•	2000000202 “Volume of the Gleason Tertiary part of the tumour”
•	2000000203 “Percentage of the total volume of the tumour occupied by the Gleason Tertiary part of the tumour”

**Comment by Spayralbe** [comment]
Hi @RomainTching 

We can definitely add these concepts to the list in pioneer_concepts.csv. 
Could you please indicate for each of them what OMOP domain_id you would like to assign them to? E.g. Observation, Measurement.

**Comment by RomainTching** [comment]
Hi @Spayralbe 
They would be Measurements! Thank you!
